import Head from 'next/head'
import Main from '../components/Main'
import { Inter } from 'next/font/google'
import About from '../components/About'
import Services from '../components/Services'
import Portfolio from '../components/Portfolio'
import Contact from '../components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Digitalizamos tu marca.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Main/>
      <About/>
      <Services/>
      <Portfolio/>
      <Contact/>
    </div>
  )
}
